<?php
/**
 * Created by PhpStorm.
 * User: WAO
 * Date: 31/05/2018
 * Time: 11:46 CH
 */

namespace App\Models\Backend;


use Illuminate\Database\Eloquent\Model;

class News extends Model
{


    protected $table = 'new';

    protected $fillable = ['id', 'new_image', 'new_name', 'new_title', 'new_content', 'new_view_count', 'menu_id', 'new_status', 'new_type', 'created_at', 'updated_at'];





    public function getAll(){
        return $this->orderBy('id', 'desc')->paginate();
    }

    public function store(array  $attribute){

        return $this->insert($attribute);
    }

    public function getItem($id){
        return $this->where('id', $id)->first();
    }

    public function updates(array $attributes, $id)
    {

        return $this->where('id', (int)$id)->update($attributes); // TODO: Change the autogenerated stub
    }

    public function destroys($id){
        return $this->where('id', (int)$id)->delete();
    }

    public function getListMenuOfProduct($type){
        return $this->from($this->table)->where('menu_type', $type)->get()->pluck('menu_name', 'id');
    }
}