<?php
/**
 * Created by PhpStorm.
 * User: WAO
 * Date: 24/05/2018
 * Time: 1:35 SA
 */

namespace App\Models\Backend;


use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{

    protected $table ='slider';
    protected $primaryKey = 'id';
    protected $fillable =['id','slider_type', 'slider_name', 'slider_image', 'slider_title', 'created_at', 'updated_at', 'slider_status'];


    public function getAll(){
        return $this->paginate();
    }


    public function store(array $attribute){
        return $this->insert($attribute);
    }

    public function getItem($id){
        return $this->where('id', $id)->first();
    }

    public function destroys($id){
        return $this->where('id', (int)$id)->delete();
    }
    public function updates(array $attributes, $id)
    {

        return $this->where('id', (int)$id)->update($attributes); // TODO: Change the autogenerated stub
    }



}